#!/bin/bash

set -e

if ! git diff-index --quiet HEAD --; then
    echo "Changes in local directory, commit or clear" >&2
    exit 1
fi

SHA=$(git rev-parse HEAD)
python setup.py sdist
TARBALL="dist/cloudns_api-*-$SHA.tar.gz"
mv dist/cloudns_api-*-0.*.tar.gz "$TARBALL"

echo "Created $TARBALL"
